# Generated by Django 4.2.7 on 2023-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('genre', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies')),
            ],
        ),
    ]
